apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-app-service
  labels:
    app: my-nodejs-app
spec:
  selector:
    app: my-nodejs-app # Selects pods with this label (from the Deployment)
  ports:
    - protocol: TCP
      port: 80 # The port the Service itself will be available on
      targetPort: 3000 # The port on the Pods that the Service will forward traffic to
  type: NodePort #